gui:
  theme:
    activeBorderColor:
      - blue
      - bold
    inactiveBorderColor:
      - white
    optionsTextColor:
      - blue
    selectedLineBgColor:
      - default # set to `default` to have no background colour
    cherryPickedCommitBgColor:
      - cyan
    cherryPickedCommitFgColor:
      - blue
    unstagedChangesColor:
      - red
  nerdFontsVersion: "3"
  showFileTree: true # for rendering changes files in a tree format
  showListFooter: false # for seeing the '5 of 20' message in list panels
  showRandomTip: false
  showBottomLine: false # for hiding the bottom information line (unless it has important information to tell you)
  showCommandLog: true
  showIcons: true
confirmOnQuit: true
git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
  overrideGpg: true
keybinding:
  universal:
    return: "<Esc>"
    # return: "<C-c>"
    # prevBlock-alt: "<c-j>"
    # nextBlock-alt: "<c-k>"
notARepository: "skip" # one of: 'prompt' | 'create' | 'skip'
