-- Generated by nwg-displays on 2026-06-19 at 14:52:03. Do not edit manually.

hl.monitor({
    output = "HDMI-A-1",
    mode = "2560x1440@144.0",
    position = "6509x768",
    scale = 1.0
})
hl.monitor({
    output = "eDP-1",
    mode = "2560x1600@165.0",
    position = "3949x608",
    scale = 1.0
})
