# Bootstrap only. Existing Matugen output is never overwritten by chezmoi.
$text_color = rgba(eeeeeeff)
$entry_background_color = rgba(202020ff)
$entry_border_color = rgba(888888ff)
$entry_color = rgba(eeeeeeff)
$font_family = sans-serif
$font_family_clock = sans-serif
