#!/bin/bash
# Generated by switchwall.sh - Don't modify it by yourself.
# Time: Sun Sep 20 11:08:51 PM CST 2026

pkill -f -9 mpvpaper

for monitor in $(hyprctl monitors -j | jq -r '.[] | .name'); do
    mpvpaper -o "no-audio loop hwdec=auto scale=bilinear interpolation=no video-sync=display-resample panscan=1.0 video-zoom=0.08 load-scripts=no input-ipc-server=/tmp/mpvpaper-$monitor.sock" "$monitor" "/home/night/Pictures/Wallpapers/video/lupa-under-moonlit-depths.3840x2160.mp4" &
    sleep 0.1
done
