#!/bin/bash
# Generated by switchwall.sh - Don't modify it by yourself.
# Time: Thu Sep 17 01:28:47 PM CST 2026

pkill -f -9 mpvpaper

for monitor in $(hyprctl monitors -j | jq -r '.[] | .name'); do
    mpvpaper -o "no-audio loop hwdec=auto scale=bilinear interpolation=no video-sync=display-resample panscan=1.0 video-zoom=0.08 load-scripts=no input-ipc-server=/tmp/mpvpaper-$monitor.sock" "$monitor" "/home/night/Pictures/Wallpapers/video/Frieren Minimal Art Live Wallpaper 4K HD ｜ Anime Background for PC [90PP0pbf8Ow].mp4" &
    sleep 0.1
done
