#!/bin/bash
# Generated by switchwall.sh - Don't modify it by yourself.
# Time: Wed Sep 16 12:12:20 AM CST 2026

pkill -f -9 mpvpaper

for monitor in $(hyprctl monitors -j | jq -r '.[] | .name'); do
    nohup mpvpaper -o "no-audio loop hwdec=auto scale=bilinear interpolation=no video-sync=display-resample panscan=1.0 video-scale-x=1.0 video-scale-y=1.0 video-align-x=0.5 video-align-y=0.5 load-scripts=no" "$monitor" "/home/night/Pictures/Wallpapers/video/Frieren Minimal Art Live Wallpaper 4K HD ｜ Anime Background for PC [90PP0pbf8Ow].mp4" >/dev/null 2>&1 &
    sleep 0.1
done
