-- Generated by HyprMon. Manual changes may be overwritten.

hl.monitor({ output = "HDMI-A-1", mode = "2560x1440@143.99", position = "0x160", scale = 1.00 })
hl.monitor({ output = "eDP-2", mode = "2560x1600@165.00", position = "2560x0", scale = 1.00 })
