import QtQuick
import QtQuick.Layouts
import Quickshell
import Quickshell.Hyprland
import Quickshell.Io
import Quickshell.Wayland
import qs.services
import qs.modules.common
import qs.modules.common.widgets

ContentPage {
    id: root
    forceWidth: true

    property int secondaryWorkspace: 10
    property string selectedSecondaryMonitor: secondaryMonitor()?.name ?? ""
    property string identifyingMonitorName: ""
    property bool identifyOverlayVisible: false
    property bool applyLayoutHintVisible: false
    property string pendingLayoutCommand: ""
    property var layoutPositions: ({})
    // Detailed output data comes from `hyprctl monitors all -j`; HyprlandData
    // remains the source for the existing live layout and workspace controls.
    property var displayConfigs: ({})

    function displayConfig(monitor) {
        return displayConfigs[monitor.name] ?? {
            name: monitor.name,
            resW: monitor.width,
            resH: monitor.height,
            rate: monitor.refreshRate,
            monScale: monitor.scale,
            transform: monitor.transform,
            enabled: true,
            modes: []
        };
    }

    function updateDisplayConfig(monitor, property, value) {
        const configs = Object.assign({}, displayConfigs);
        const config = Object.assign({}, root.displayConfig(monitor));
        config[property] = value;
        configs[monitor.name] = config;
        displayConfigs = configs;
    }

    function displayResolutions(monitor) {
        const config = root.displayConfig(monitor);
        const resolutions = [];
        for (const mode of config.modes) {
            const value = `${mode.w}x${mode.h}`;
            if (!resolutions.some(option => option.value === value))
                resolutions.push({ displayName: value, value });
        }
        if (resolutions.length === 0)
            resolutions.push({ displayName: `${config.resW}x${config.resH}`, value: `${config.resW}x${config.resH}` });
        return resolutions.sort((a, b) => parseInt(b.value) - parseInt(a.value));
    }

    function displayRefreshRates(monitor) {
        const config = root.displayConfig(monitor);
        const rates = [];
        for (const mode of config.modes) {
            if (mode.w !== config.resW || mode.h !== config.resH)
                continue;
            const roundedRate = Math.round(mode.rate);
            if (!rates.some(option => option.value === roundedRate))
                rates.push({ displayName: `${roundedRate} Hz`, value: roundedRate, exactRate: mode.rate });
        }
        if (rates.length === 0)
            rates.push({ displayName: `${Math.round(config.rate)} Hz`, value: Math.round(config.rate), exactRate: config.rate });
        return rates.sort((a, b) => b.value - a.value);
    }

    function buildDisplaySpec(monitor) {
        const config = root.displayConfig(monitor);
        if (!config.enabled)
            return `${monitor.name},disable`;
        let spec = `${monitor.name},${config.resW}x${config.resH}@${Number(config.rate).toFixed(2)},${root.pendingX(monitor)}x${root.pendingY(monitor)},${config.monScale}`;
        if (config.transform !== 0)
            spec += `,transform,${config.transform}`;
        return spec;
    }

    function displayEvalCommand(monitor) {
        const config = root.displayConfig(monitor);
        if (!config.enabled)
            return `hl.monitor({output="${monitor.name}", mode="disable"})`;
        let command = `hl.monitor({output="${monitor.name}", mode="${config.resW}x${config.resH}@${Number(config.rate).toFixed(2)}", position="${root.pendingX(monitor)}x${root.pendingY(monitor)}", scale=${config.monScale}`;
        if (config.transform !== 0)
            command += `, transform=${config.transform}`;
        return `${command}})`;
    }

    function applyDisplaySettings(monitor, save) {
        const spec = root.buildDisplaySpec(monitor);
        // Hyprland 0.56 removed the legacy `keyword monitor` parser.
        displayApplyProcess.apply(root.displayEvalCommand(monitor));
        if (save) {
            // monitors.lua is already included by hyprland.lua. Save every
            // output so editing one monitor cannot discard the others.
            const lines = ["-- Generated by the Settings Monitor page.\n"];
            for (const output of root.monitors()) {
                const savedSpec = root.buildDisplaySpec(output);
                if (root.displayConfig(output).enabled) {
                    const parts = savedSpec.split(",");
                    lines.push(`hl.monitor({ output = \"${parts[0]}\", mode = \"${parts[1]}\", position = \"${parts[2]}\", scale = ${parts[3]}${parts.length > 4 ? `, transform = ${parts[5]}` : ""} })`);
                }
            }
            Quickshell.execDetached(["bash", "-c", `printf '%s\\n' '${lines.join("\\n").replace(/'/g, "'\\\"'\\\"")}' > \"${Directories.config}/hypr/monitors.lua\"`]);
        }
    }

    Process {
        id: displayApplyProcess
        property string queuedCommand: ""

        function apply(command) {
            // A monitor reconfiguration can briefly outlive hyprctl itself.
            // Serialize rapid consecutive clicks so the latest choice is never
            // lost to a still-running previous request.
            if (running) {
                queuedCommand = command;
                return;
            }
            exec(["hyprctl", "eval", command]);
        }

        onExited: {
            if (queuedCommand.length > 0) {
                const nextCommand = queuedCommand;
                queuedCommand = "";
                exec(["hyprctl", "eval", nextCommand]);
                return;
            }
            // Hyprland applies output changes asynchronously. Polling
            // immediately reads old values and overwrites the selection.
            refreshTimer.restart();
            displayRepollTimer.restart();
        }
    }

    Process {
        id: displayPoller
        running: true
        command: ["hyprctl", "monitors", "all", "-j"]

        function refresh() {
            running = false;
            Qt.callLater(() => running = true);
        }
        stdout: StdioCollector {
            onStreamFinished: {
                try {
                    const configs = {};
                    for (const output of JSON.parse(text.trim())) {
                        const modes = [];
                        for (const modeText of (output.availableModes ?? [])) {
                            const match = modeText.match(/(\d+)x(\d+)@([\d.]+)Hz/);
                            if (!match)
                                continue;
                            const mode = { w: parseInt(match[1]), h: parseInt(match[2]), rate: parseFloat(match[3]) };
                            if (!modes.some(existing => existing.w === mode.w && existing.h === mode.h && Math.round(existing.rate) === Math.round(mode.rate)))
                                modes.push(mode);
                        }
                        configs[output.name] = {
                            name: output.name,
                            resW: output.width,
                            resH: output.height,
                            rate: output.refreshRate ?? 60,
                            monScale: output.scale ?? 1,
                            transform: output.transform ?? 0,
                            enabled: !output.disabled,
                            modes
                        };
                    }
                    root.displayConfigs = configs;
                } catch (error) {
                    console.log("[MonitorConfig] Could not parse monitor details:", error);
                }
            }
        }
    }

    function monitors() {
        return HyprlandData.monitors.slice().sort((a, b) => a.x === b.x ? a.y - b.y : a.x - b.x);
    }

    function primaryMonitor() {
        const list = root.monitors();
        return list.find(monitor => monitor.focused) ?? list[0] ?? null;
    }

    function secondaryMonitor() {
        const primary = root.primaryMonitor();
        const list = root.monitors().filter(monitor => monitor.name !== primary?.name);
        return list[0] ?? primary ?? null;
    }

    function monitorWidth(monitor) {
        return (monitor.transform % 2 === 1) ? monitor.height : monitor.width;
    }

    function monitorHeight(monitor) {
        return (monitor.transform % 2 === 1) ? monitor.width : monitor.height;
    }

    function pendingX(monitor) {
        return layoutPositions[monitor.name]?.x ?? monitor.x;
    }

    function pendingY(monitor) {
        return layoutPositions[monitor.name]?.y ?? monitor.y;
    }

    function layoutBounds() {
        const list = root.monitors();
        if (list.length === 0)
            return { minX: 0, minY: 0, maxX: 1, maxY: 1, width: 1, height: 1 };

        let minX = Math.min(...list.map(monitor => root.pendingX(monitor)));
        let minY = Math.min(...list.map(monitor => root.pendingY(monitor)));
        let maxX = Math.max(...list.map(monitor => root.pendingX(monitor) + root.monitorWidth(monitor)));
        let maxY = Math.max(...list.map(monitor => root.pendingY(monitor) + root.monitorHeight(monitor)));
        return { minX, minY, maxX, maxY, width: Math.max(maxX - minX, 1), height: Math.max(maxY - minY, 1) };
    }

    function canvasScale() {
        const bounds = root.layoutBounds();
        return Math.min((layoutCanvas.width - 48) / bounds.width, (layoutCanvas.height - 48) / bounds.height);
    }

    function setMonitorPosition(monitor, x, y) {
        const positions = Object.assign({}, layoutPositions);
        positions[monitor.name] = {
            x: Math.round(x),
            y: Math.round(y)
        };
        layoutPositions = positions;
    }

    function snapHorizontalLayout() {
        const ordered = root.monitors().slice().sort((a, b) => {
            const centerA = root.pendingX(a) + root.monitorWidth(a) / 2;
            const centerB = root.pendingX(b) + root.monitorWidth(b) / 2;
            return centerA === centerB ? root.pendingY(a) - root.pendingY(b) : centerA - centerB;
        });
        const positions = {};
        let x = 0;
        for (const monitor of ordered) {
            positions[monitor.name] = {
                x,
                y: Math.round(root.pendingY(monitor))
            };
            x += root.monitorWidth(monitor);
        }
        layoutPositions = positions;
    }

    function updateDraggedMonitor(monitor, visualX, visualY) {
        const bounds = root.layoutBounds();
        const scale = root.canvasScale();
        root.setMonitorPosition(monitor, bounds.minX + (visualX - 24) / scale, bounds.minY + (visualY - 24) / scale);
        root.snapHorizontalLayout();
    }

    function setMonitorAxis(monitor, axis, valueText) {
        const value = parseInt(valueText);
        if (isNaN(value))
            return;

        if (axis === "x")
            root.setMonitorPosition(monitor, value, root.pendingY(monitor));
        else
            root.setMonitorPosition(monitor, root.pendingX(monitor), value);
        root.snapHorizontalLayout();
        root.triggerApplyLayoutHint();
    }

    function triggerApplyLayoutHint() {
        applyLayoutHintVisible = true;
        applyLayoutHintTimer.restart();
    }

    function resetLayout() {
        layoutPositions = ({});
    }

    function applyLayout() {
        pendingLayoutCommand = root.monitors().map(monitor => root.displayEvalCommand(monitor)).join("; ");
        Quickshell.execDetached(["hyprctl", "eval", pendingLayoutCommand]);
        layoutStabilizeTimer.restart();
        refreshTimer.restart();
        displayRepollTimer.restart();
    }

    function identifyMonitor(monitor) {
        if (!monitor)
            return;
        identifyingMonitorName = monitor.name;
        identifyOverlayVisible = true;
        identifyTimer.restart();
    }

    function identifyAllMonitors() {
        identifyingMonitorName = "__all__";
        identifyOverlayVisible = true;
        identifyTimer.restart();
    }

    function applySecondaryWorkspace() {
        const monitor = selectedSecondaryMonitor || root.secondaryMonitor()?.name || "";
        if (!monitor)
            return;
        Quickshell.execDetached(["bash", "-c", `hyprctl dispatch focusmonitor '${monitor}'; hyprctl dispatch workspace ${secondaryWorkspace}; hyprctl dispatch moveworkspacetomonitor ${secondaryWorkspace} '${monitor}'`]);
        refreshTimer.restart();
    }

    Component.onCompleted: {
        HyprlandData.updateMonitors();
        HyprlandData.updateWorkspaces();
    }

    Connections {
        target: HyprlandData

        function onMonitorsChanged() {
            if (!root.selectedSecondaryMonitor && root.secondaryMonitor())
                root.selectedSecondaryMonitor = root.secondaryMonitor().name;
        }
    }

    Timer {
        id: refreshTimer
        interval: 700
        repeat: false
        onTriggered: HyprlandData.updateAll()
    }

    Timer {
        id: displayRepollTimer
        interval: 1500
        repeat: false
        onTriggered: displayPoller.refresh()
    }

    Timer {
        id: layoutStabilizeTimer
        interval: 650
        repeat: false
        onTriggered: {
            if (!root.pendingLayoutCommand)
                return;
            Quickshell.execDetached(["hyprctl", "eval", root.pendingLayoutCommand]);
            HyprlandData.updateAll();
        }
    }

    Timer {
        id: applyLayoutHintTimer
        interval: 2000
        repeat: false
        onTriggered: root.applyLayoutHintVisible = false
    }

    Timer {
        id: identifyTimer
        interval: 1800
        repeat: false
        onTriggered: {
            root.identifyOverlayVisible = false;
            root.identifyingMonitorName = "";
        }
    }

    component MonitorItem: Rectangle {
        id: itemRoot
        required property var monitorData
        // A single display is the common laptop case; show its controls
        // immediately instead of hiding every editable option behind a row.
        property bool expanded: root.monitors().length === 1
        readonly property bool active: monitorData.focused

        Layout.fillWidth: true
        implicitHeight: monitorItemContent.implicitHeight + 16
        radius: Appearance.rounding.normal
        color: itemRoot.expanded ? Appearance.colors.colLayer3 : monitorMouseArea.containsMouse ? Appearance.colors.colLayer3Hover : "transparent"
        clip: true

        Behavior on implicitHeight {
            animation: Appearance.animation.elementMove.numberAnimation.createObject(this)
        }
        Behavior on color {
            animation: Appearance.animation.elementMoveFast.colorAnimation.createObject(this)
        }

        ColumnLayout {
            id: monitorItemContent
            anchors.fill: parent
            anchors.margins: 8
            spacing: 10

            RowLayout {
                Layout.fillWidth: true
                spacing: 10

                Item {
                    Layout.fillWidth: true
                    implicitHeight: monitorHeader.implicitHeight

                    MouseArea {
                        id: monitorMouseArea
                        anchors.fill: parent
                        cursorShape: Qt.PointingHandCursor
                        hoverEnabled: true
                        onClicked: itemRoot.expanded = !itemRoot.expanded
                    }

                    RowLayout {
                        id: monitorHeader
                        anchors.fill: parent
                        spacing: 10

                        MaterialSymbol {
                            text: itemRoot.active ? "desktop_windows" : "monitor"
                            iconSize: Appearance.font.pixelSize.larger
                            color: Appearance.colors.colOnSurfaceVariant
                        }

                        ColumnLayout {
                            Layout.fillWidth: true
                            spacing: 0

                            StyledText {
                                Layout.fillWidth: true
                                text: itemRoot.monitorData.name
                                color: Appearance.colors.colOnSurfaceVariant
                                elide: Text.ElideRight
                                textFormat: Text.PlainText
                            }

                            StyledText {
                                Layout.fillWidth: true
                                text: `${itemRoot.monitorData.width}x${itemRoot.monitorData.height} @ ${Math.round(itemRoot.monitorData.refreshRate)}Hz - ${root.pendingX(itemRoot.monitorData)}, ${root.pendingY(itemRoot.monitorData)} - Workspace ${itemRoot.monitorData.activeWorkspace?.id ?? "?"}`
                                color: Appearance.colors.colSubtext
                                font.pixelSize: Appearance.font.pixelSize.smallie
                                elide: Text.ElideRight
                            }
                        }

                    }
                }

                DialogButton {
                    buttonText: Translation.tr("Identify")
                    onClicked: root.identifyMonitor(itemRoot.monitorData)
                }

                MaterialSymbol {
                    text: "keyboard_arrow_down"
                    iconSize: Appearance.font.pixelSize.larger
                    color: Appearance.colors.colSubtext
                    rotation: itemRoot.expanded ? 180 : 0

                    Behavior on rotation {
                        NumberAnimation {
                            duration: 150
                            easing.type: Easing.OutCubic
                        }
                    }

                    MouseArea {
                        anchors.fill: parent
                        cursorShape: Qt.PointingHandCursor
                        onClicked: itemRoot.expanded = !itemRoot.expanded
                    }
                }
            }

            RowLayout {
                visible: itemRoot.expanded
                Layout.fillWidth: true
                spacing: 10

                MaterialSymbol {
                    text: "open_with"
                    iconSize: Appearance.font.pixelSize.larger
                    color: Appearance.colors.colSubtext
                }

                StyledText {
                    text: Translation.tr("Pos X")
                    color: Appearance.colors.colOnSecondaryContainer
                }

                MaterialTextField {
                    id: posXField
                    Layout.preferredWidth: 82
                    Layout.preferredHeight: 44
                    font.pixelSize: Appearance.font.pixelSize.smallie
                    text: `${root.pendingX(itemRoot.monitorData)}`
                    validator: IntValidator {
                        bottom: -20000
                        top: 20000
                    }
                    inputMethodHints: Qt.ImhFormattedNumbersOnly
                    onAccepted: focus = false
                    onEditingFinished: root.setMonitorAxis(itemRoot.monitorData, "x", text)
                }

                StyledText {
                    text: Translation.tr("Pos Y")
                    color: Appearance.colors.colOnSecondaryContainer
                }

                MaterialTextField {
                    id: posYField
                    Layout.preferredWidth: 82
                    Layout.preferredHeight: 44
                    font.pixelSize: Appearance.font.pixelSize.smallie
                    text: `${root.pendingY(itemRoot.monitorData)}`
                    validator: IntValidator {
                        bottom: -20000
                        top: 20000
                    }
                    inputMethodHints: Qt.ImhFormattedNumbersOnly
                    onAccepted: focus = false
                    onEditingFinished: root.setMonitorAxis(itemRoot.monitorData, "y", text)
                }

                StyledText {
                    Layout.fillWidth: true
                    text: Translation.tr("Positions are snapped to avoid overlap.")
                    color: Appearance.colors.colSubtext
                    wrapMode: Text.Wrap
                }
            }

            ColumnLayout {
                visible: itemRoot.expanded
                Layout.fillWidth: true
                spacing: 6

                ConfigSwitch {
                    buttonIcon: "power_settings_new"
                    text: Translation.tr("Enabled")
                    checked: root.displayConfig(itemRoot.monitorData).enabled
                    enabled: !checked || root.monitors().filter(monitor => root.displayConfig(monitor).enabled).length > 1
                    onCheckedChanged: {
                        if (checked !== root.displayConfig(itemRoot.monitorData).enabled)
                            root.updateDisplayConfig(itemRoot.monitorData, "enabled", checked);
                    }
                    StyledToolTip {
                        text: Translation.tr("You cannot disable the only active monitor")
                    }
                }

                ContentSubsection {
                    Layout.fillWidth: true
                    enabled: root.displayConfig(itemRoot.monitorData).enabled
                    title: Translation.tr("Resolution")

                    ConfigSelectionArray {
                        currentValue: `${root.displayConfig(itemRoot.monitorData).resW}x${root.displayConfig(itemRoot.monitorData).resH}`
                        options: root.displayResolutions(itemRoot.monitorData)
                        onSelected: newValue => {
                            const dimensions = newValue.split("x");
                            root.updateDisplayConfig(itemRoot.monitorData, "resW", parseInt(dimensions[0]));
                            root.updateDisplayConfig(itemRoot.monitorData, "resH", parseInt(dimensions[1]));
                            const rates = root.displayRefreshRates(itemRoot.monitorData);
                            if (rates.length > 0)
                                root.updateDisplayConfig(itemRoot.monitorData, "rate", rates[0].exactRate);
                        }
                    }
                }

                ConfigRow {
                    Layout.fillWidth: true
                    enabled: root.displayConfig(itemRoot.monitorData).enabled

                    ContentSubsection {
                        title: Translation.tr("Refresh rate")
                        Layout.fillWidth: true

                        ConfigSelectionArray {
                            currentValue: Math.round(root.displayConfig(itemRoot.monitorData).rate)
                            options: root.displayRefreshRates(itemRoot.monitorData)
                            onSelected: newValue => {
                                const selected = root.displayRefreshRates(itemRoot.monitorData).find(option => option.value === newValue);
                                root.updateDisplayConfig(itemRoot.monitorData, "rate", selected?.exactRate ?? newValue);
                            }
                        }
                    }

                    ContentSubsection {
                        title: Translation.tr("Scale")
                        Layout.fillWidth: true

                        ConfigSelectionArray {
                            currentValue: root.displayConfig(itemRoot.monitorData).monScale
                            options: {
                                const scales = [1, 1.25, 1.5, 1.75, 2];
                                const current = root.displayConfig(itemRoot.monitorData).monScale;
                                const options = scales.map(scale => ({ displayName: `${Math.round(scale * 100)}%`, value: scale }));
                                if (!scales.includes(current))
                                    options.unshift({ displayName: `${Math.round(current * 100)}%`, value: current });
                                return options;
                            }
                            onSelected: newValue => root.updateDisplayConfig(itemRoot.monitorData, "monScale", newValue)
                        }
                    }
                }

                ContentSubsection {
                    Layout.fillWidth: true
                    enabled: root.displayConfig(itemRoot.monitorData).enabled
                    title: Translation.tr("Rotation")

                    ConfigSelectionArray {
                        currentValue: root.displayConfig(itemRoot.monitorData).transform
                        onSelected: newValue => root.updateDisplayConfig(itemRoot.monitorData, "transform", newValue)
                        options: [
                            { displayName: Translation.tr("Normal"), icon: "stay_current_landscape", value: 0 },
                            { displayName: "90°", icon: "rotate_90_degrees_cw", value: 1 },
                            { displayName: "180°", icon: "sync", value: 2 },
                            { displayName: "270°", icon: "rotate_90_degrees_ccw", value: 3 }
                        ]
                    }
                }

                ConfigRow {
                    Layout.fillWidth: true

                    DialogButton {
                        Layout.fillWidth: true
                        buttonText: Translation.tr("Apply display settings")
                        onClicked: root.applyDisplaySettings(itemRoot.monitorData, false)
                    }

                    DialogButton {
                        Layout.fillWidth: true
                        buttonText: Translation.tr("Apply and save")
                        onClicked: root.applyDisplaySettings(itemRoot.monitorData, true)
                    }
                }
            }
        }
    }

    Variants {
        model: Quickshell.screens

        PanelWindow {
            id: identifyWindow
            required property var modelData
            readonly property HyprlandMonitor monitor: Hyprland.monitorFor(identifyWindow.screen)

            screen: modelData
            visible: root.identifyOverlayVisible && (root.identifyingMonitorName === "__all__" || monitor?.name === root.identifyingMonitorName)
            color: "transparent"
            exclusionMode: ExclusionMode.Ignore
            WlrLayershell.namespace: "quickshell:settings-monitor-identify"
            WlrLayershell.layer: WlrLayer.Overlay
            WlrLayershell.keyboardFocus: WlrKeyboardFocus.None

            anchors {
                top: true
                bottom: true
                left: true
                right: true
            }

            Rectangle {
                anchors.centerIn: parent
                implicitWidth: identifyText.implicitWidth + 64
                implicitHeight: identifyText.implicitHeight + 40
                radius: Appearance.rounding.large
                color: Appearance.colors.colPrimaryContainer
                border.width: 2
                border.color: Appearance.colors.colPrimary

                StyledText {
                    id: identifyText
                    anchors.centerIn: parent
                    text: root.identifyingMonitorName === "__all__" ? (monitor?.name ?? "") : root.identifyingMonitorName
                    color: Appearance.colors.colOnPrimaryContainer
                    font.pixelSize: Appearance.font.pixelSize.title
                    font.weight: Font.Bold
                }
            }
        }
    }

    ColumnLayout {
        Layout.fillWidth: true
        spacing: 6

        RowLayout {
            Layout.fillWidth: true
            Layout.leftMargin: -6
            spacing: 6

            OptionalMaterialSymbol {
                icon: "monitor"
                iconSize: Appearance.font.pixelSize.hugeass
            }

            StyledText {
                Layout.fillWidth: true
                text: Translation.tr("Connected monitors")
                font.pixelSize: Appearance.font.pixelSize.larger
                font.weight: Font.Medium
                color: Appearance.colors.colOnSecondaryContainer
            }

            DialogButton {
                buttonText: Translation.tr("KDE display settings")
                onClicked: Quickshell.execDetached(["systemsettings", "display"])
            }
        }

        ContentSection {
            icon: "dashboard"
            title: Translation.tr("Layout")

            ConfigRow {
                DialogButton {
                    id: applyLayoutButton
                    buttonText: Translation.tr("Apply layout")
                    enabled: root.monitors().length > 0
                    colBackground: root.applyLayoutHintVisible ? Appearance.colors.colLayer3Hover : "transparent"
                    onClicked: root.applyLayout()
                }

                DialogButton {
                    buttonText: Translation.tr("Reset")
                    onClicked: root.resetLayout()
                }

                StyledText {
                    Layout.fillWidth: true
                    text: Translation.tr("Drag monitors to change their runtime position.")
                    color: Appearance.colors.colSubtext
                    wrapMode: Text.Wrap
                }
            }

            Rectangle {
                id: layoutCanvas
                Layout.fillWidth: true
                implicitHeight: 260
                radius: Appearance.rounding.large
                color: Appearance.colors.colLayer1
                border.width: 1
                border.color: Appearance.colors.colLayer2
                clip: true

                Repeater {
                    model: root.monitors()

                    Rectangle {
                        id: monitorRect
                        required property var modelData
                        readonly property var bounds: root.layoutBounds()
                        readonly property real scaleFactor: root.canvasScale()
                        readonly property real baseX: 24 + (root.pendingX(modelData) - bounds.minX) * scaleFactor
                        readonly property real baseY: 24 + (root.pendingY(modelData) - bounds.minY) * scaleFactor

                        width: Math.max(root.monitorWidth(modelData) * scaleFactor, 88)
                        height: Math.max(root.monitorHeight(modelData) * scaleFactor, 56)
                        x: baseX
                        y: baseY
                        radius: Appearance.rounding.normal
                        color: modelData.focused ? Appearance.colors.colPrimaryContainer : Appearance.colors.colLayer2
                        border.width: 1
                        border.color: modelData.focused ? Appearance.colors.colPrimary : Appearance.colors.colLayer3
                        z: dragArea.drag.active ? 10 : 1

                        ColumnLayout {
                            anchors.centerIn: parent
                            width: parent.width - 16
                            spacing: 0

                            StyledText {
                                Layout.fillWidth: true
                                horizontalAlignment: Text.AlignHCenter
                                text: modelData.name
                                color: modelData.focused ? Appearance.colors.colOnPrimaryContainer : Appearance.colors.colOnLayer2
                                font.weight: Font.Medium
                                elide: Text.ElideRight
                            }

                            StyledText {
                                Layout.fillWidth: true
                                horizontalAlignment: Text.AlignHCenter
                                text: `${modelData.width}x${modelData.height}`
                                color: Appearance.colors.colSubtext
                                font.pixelSize: Appearance.font.pixelSize.smallie
                                elide: Text.ElideRight
                            }
                        }

                        MouseArea {
                            id: dragArea
                            anchors.fill: parent
                            cursorShape: Qt.SizeAllCursor
                            drag.target: parent
                            drag.minimumX: 8
                            drag.minimumY: 8
                            drag.maximumX: layoutCanvas.width - parent.width - 8
                            drag.maximumY: layoutCanvas.height - parent.height - 8
                            onReleased: {
                                root.updateDraggedMonitor(modelData, parent.x, parent.y);
                                monitorRect.x = Qt.binding(() => monitorRect.baseX);
                                monitorRect.y = Qt.binding(() => monitorRect.baseY);
                            }
                        }
                    }
                }
            }
        }

        ColumnLayout {
            Layout.fillWidth: true
            spacing: 6

            Repeater {
                model: root.monitors()

                MonitorItem {
                    required property var modelData
                    monitorData: modelData
                }
            }

            ConfigRow {
                DialogButton {
                    buttonText: Translation.tr("Refresh")
                    onClicked: HyprlandData.updateAll()
                }

                StyledText {
                    text: root.monitors().length === 1
                        ? Translation.tr("1 monitor connected")
                        : Translation.tr("%1 monitors connected").arg(root.monitors().length)
                    color: Appearance.colors.colSubtext
                    wrapMode: Text.Wrap
                }

                Item {
                    Layout.fillWidth: true
                }

                DialogButton {
                    buttonText: Translation.tr("Identify all")
                    enabled: root.monitors().length > 0
                    onClicked: root.identifyAllMonitors()
                }
            }
        }
    }

    ContentSection {
        icon: "workspaces"
        title: Translation.tr("Secondary workspace")

        ConfigRow {
            StyledText {
                Layout.fillWidth: true
                Layout.leftMargin: 14
                text: Translation.tr("Choose where the secondary monitor should land by default.")
                color: Appearance.colors.colSubtext
                wrapMode: Text.Wrap
            }
        }

        ConfigRow {
            StyledText {
                text: Translation.tr("Monitor")
                color: Appearance.colors.colOnSecondaryContainer
            }

            StyledComboBox {
                Layout.fillWidth: true
                model: root.monitors().map(monitor => monitor.name)
                currentIndex: Math.max(0, root.monitors().map(monitor => monitor.name).indexOf(root.selectedSecondaryMonitor))
                onActivated: index => root.selectedSecondaryMonitor = root.monitors()[index]?.name ?? ""
            }
        }

        ConfigRow {
            StyledText {
                Layout.fillWidth: true
                text: Translation.tr("Workspace")
                color: Appearance.colors.colOnSecondaryContainer
            }

            StyledSpinBox {
                from: 1
                to: 100
                value: root.secondaryWorkspace
                onValueChanged: root.secondaryWorkspace = value
            }

            DialogButton {
                buttonText: Translation.tr("Apply")
                onClicked: root.applySecondaryWorkspace()
            }
        }
    }
}
